vich_uploader:
    db_driver: orm

    mappings:
       media_object:
           uri_prefix: '%upload_directory%'
           upload_destination: '%kernel.project_dir%/public%upload_directory%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
