stages:
  - build
  - deploy

build_project:
  stage: build
  image: php:7.4-cli
  script:
    - echo "Téléchargement de Composer 1.x..."
    - curl -sS https://getcomposer.org/installer | php -- --version=1.10.22
    - php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
    - echo "Préparation des fichiers pour le déploiement..."
    - tar -czf project.tar.gz . --exclude-vcs --exclude=.gitlab-ci.yml
  artifacts:
    paths:
      - project.tar.gz

deploy_to_server:
  stage: deploy
  only:
    - main
  dependencies:
    - build_project
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    # Gestion de la passphrase de la clé SSH
    - echo -e '#!/usr/bin/env bash\necho "$SSH_PASSPHRASE"' > ssh_askpass.sh
    - chmod +x ssh_askpass.sh
    - export SSH_ASKPASS="$CI_PROJECT_DIR/ssh_askpass.sh"
    - setsid ssh-add < /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Déploiement sur le serveur..."
    - scp -P $SSH_PORT project.tar.gz $SSH_USER@$SSH_HOST:~/public_html/
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
      cd ~/public_html &&
      tar -xzf project.tar.gz &&
      rm project.tar.gz &&
      php bin/console doctrine:migrations:migrate -n &&
      php bin/console cache:clear
      "
  environment:
    name: production
    url: https://reservation.bethrivkah.fr


